import 'package:flutter/material.dart';
import 'flutter_icon_data.dart';

/// all Icons under EvilIcons
///
/// http://evil-icons.io
class EvilIcons {
  EvilIcons._();
  static IconData archive =  FlutterIconData.evilIcons(61696);
  static IconData arrow_down =  FlutterIconData.evilIcons(61697);
  static IconData arrow_left =  FlutterIconData.evilIcons(61698);
  static IconData arrow_right =  FlutterIconData.evilIcons(61699);
  static IconData arrow_up =  FlutterIconData.evilIcons(61700);
  static IconData bell =  FlutterIconData.evilIcons(61701);
  static IconData calendar =  FlutterIconData.evilIcons(61702);
  static IconData camera =  FlutterIconData.evilIcons(61703);
  static IconData cart =  FlutterIconData.evilIcons(61704);
  static IconData chart =  FlutterIconData.evilIcons(61705);
  static IconData check =  FlutterIconData.evilIcons(61706);
  static IconData chevron_down =  FlutterIconData.evilIcons(61707);
  static IconData chevron_left =  FlutterIconData.evilIcons(61708);
  static IconData chevron_right =  FlutterIconData.evilIcons(61709);
  static IconData chevron_up =  FlutterIconData.evilIcons(61710);
  static IconData clock =  FlutterIconData.evilIcons(61711);
  static IconData close =  FlutterIconData.evilIcons(61712);
  static IconData close_o =  FlutterIconData.evilIcons(61713);
  static IconData comment =  FlutterIconData.evilIcons(61714);
  static IconData credit_card =  FlutterIconData.evilIcons(61715);
  static IconData envelope =  FlutterIconData.evilIcons(61716);
  static IconData exclamation =  FlutterIconData.evilIcons(61717);
  static IconData external_link =  FlutterIconData.evilIcons(61718);
  static IconData eye =  FlutterIconData.evilIcons(61719);
  static IconData gear =  FlutterIconData.evilIcons(61720);
  static IconData heart =  FlutterIconData.evilIcons(61721);
  static IconData image =  FlutterIconData.evilIcons(61722);
  static IconData like =  FlutterIconData.evilIcons(61723);
  static IconData link =  FlutterIconData.evilIcons(61724);
  static IconData location =  FlutterIconData.evilIcons(61725);
  static IconData lock =  FlutterIconData.evilIcons(61726);
  static IconData minus =  FlutterIconData.evilIcons(61727);
  static IconData navicon =  FlutterIconData.evilIcons(61728);
  static IconData paperclip =  FlutterIconData.evilIcons(61729);
  static IconData pencil =  FlutterIconData.evilIcons(61730);
  static IconData play =  FlutterIconData.evilIcons(61731);
  static IconData plus =  FlutterIconData.evilIcons(61732);
  static IconData pointer =  FlutterIconData.evilIcons(61733);
  static IconData question =  FlutterIconData.evilIcons(61734);
  static IconData redo =  FlutterIconData.evilIcons(61735);
  static IconData refresh =  FlutterIconData.evilIcons(61736);
  static IconData retweet =  FlutterIconData.evilIcons(61737);
  static IconData sc_facebook =  FlutterIconData.evilIcons(61738);
  static IconData sc_github =  FlutterIconData.evilIcons(61739);
  static IconData sc_google_plus =  FlutterIconData.evilIcons(61740);
  static IconData sc_instagram =  FlutterIconData.evilIcons(61741);
  static IconData sc_linkedin =  FlutterIconData.evilIcons(61742);
  static IconData sc_odnoklassniki =
       FlutterIconData.evilIcons(61743);
  static IconData sc_pinterest =  FlutterIconData.evilIcons(61744);
  static IconData sc_skype =  FlutterIconData.evilIcons(61745);
  static IconData sc_soundcloud =  FlutterIconData.evilIcons(61746);
  static IconData sc_telegram =  FlutterIconData.evilIcons(61747);
  static IconData sc_tumblr =  FlutterIconData.evilIcons(61748);
  static IconData sc_twitter =  FlutterIconData.evilIcons(61749);
  static IconData sc_vimeo =  FlutterIconData.evilIcons(61750);
  static IconData sc_vk =  FlutterIconData.evilIcons(61751);
  static IconData sc_youtube =  FlutterIconData.evilIcons(61752);
  static IconData search =  FlutterIconData.evilIcons(61753);
  static IconData share_apple =  FlutterIconData.evilIcons(61754);
  static IconData share_google =  FlutterIconData.evilIcons(61755);
  static IconData spinner =  FlutterIconData.evilIcons(61756);
  static IconData spinner_2 =  FlutterIconData.evilIcons(61757);
  static IconData spinner_3 =  FlutterIconData.evilIcons(61758);
  static IconData star =  FlutterIconData.evilIcons(61759);
  static IconData tag =  FlutterIconData.evilIcons(61760);
  static IconData trash =  FlutterIconData.evilIcons(61761);
  static IconData trophy =  FlutterIconData.evilIcons(61762);
  static IconData undo =  FlutterIconData.evilIcons(61763);
  static IconData unlock =  FlutterIconData.evilIcons(61764);
  static IconData user =  FlutterIconData.evilIcons(61765);
}
