import 'package:flutter/material.dart';
import 'flutter_icon_data.dart';

/// all Icons under Octicons
///
/// http://octicons.github.com
class Octicons {
  Octicons._();
  static IconData alert =  FlutterIconData.octicons(61696);
  static IconData archive =  FlutterIconData.octicons(61697);
  static IconData arrow_down =  FlutterIconData.octicons(61698);
  static IconData arrow_left =  FlutterIconData.octicons(61699);
  static IconData arrow_right =  FlutterIconData.octicons(61700);
  static IconData arrow_small_down =
       FlutterIconData.octicons(61701);
  static IconData arrow_small_left =
       FlutterIconData.octicons(61702);
  static IconData arrow_small_right =
       FlutterIconData.octicons(61703);
  static IconData arrow_small_up =  FlutterIconData.octicons(61704);
  static IconData arrow_up =  FlutterIconData.octicons(61705);
  static IconData beaker =  FlutterIconData.octicons(61706);
  static IconData bell =  FlutterIconData.octicons(61707);
  static IconData bold =  FlutterIconData.octicons(61708);
  static IconData book =  FlutterIconData.octicons(61709);
  static IconData bookmark =  FlutterIconData.octicons(61710);
  static IconData briefcase =  FlutterIconData.octicons(61711);
  static IconData broadcast =  FlutterIconData.octicons(61712);
  static IconData browser =  FlutterIconData.octicons(61713);
  static IconData bug =  FlutterIconData.octicons(61714);
  static IconData calendar =  FlutterIconData.octicons(61715);
  static IconData check =  FlutterIconData.octicons(61716);
  static IconData checklist =  FlutterIconData.octicons(61717);
  static IconData chevron_down =  FlutterIconData.octicons(61718);
  static IconData chevron_left =  FlutterIconData.octicons(61719);
  static IconData chevron_right =  FlutterIconData.octicons(61720);
  static IconData chevron_up =  FlutterIconData.octicons(61721);
  static IconData circle_slash =  FlutterIconData.octicons(61722);
  static IconData circuit_board =  FlutterIconData.octicons(61723);
  static IconData clippy =  FlutterIconData.octicons(61724);
  static IconData clock =  FlutterIconData.octicons(61725);
  static IconData cloud_download =  FlutterIconData.octicons(61726);
  static IconData cloud_upload =  FlutterIconData.octicons(61727);
  static IconData code =  FlutterIconData.octicons(61728);
  static IconData comment =  FlutterIconData.octicons(61729);
  static IconData comment_discussion =
       FlutterIconData.octicons(61730);
  static IconData credit_card =  FlutterIconData.octicons(61731);
  static IconData dash =  FlutterIconData.octicons(61732);
  static IconData dashboard =  FlutterIconData.octicons(61733);
  static IconData database =  FlutterIconData.octicons(61734);
  static IconData desktop_download =
       FlutterIconData.octicons(61735);
  static IconData device_camera =  FlutterIconData.octicons(61736);
  static IconData device_camera_video =
       FlutterIconData.octicons(61737);
  static IconData device_desktop =  FlutterIconData.octicons(61738);
  static IconData device_mobile =  FlutterIconData.octicons(61739);
  static IconData diff =  FlutterIconData.octicons(61740);
  static IconData diff_added =  FlutterIconData.octicons(61741);
  static IconData diff_ignored =  FlutterIconData.octicons(61742);
  static IconData diff_modified =  FlutterIconData.octicons(61743);
  static IconData diff_removed =  FlutterIconData.octicons(61744);
  static IconData diff_renamed =  FlutterIconData.octicons(61745);
  static IconData ellipsis =  FlutterIconData.octicons(61746);
  static IconData eye =  FlutterIconData.octicons(61747);
  static IconData file =  FlutterIconData.octicons(61748);
  static IconData file_binary =  FlutterIconData.octicons(61749);
  static IconData file_code =  FlutterIconData.octicons(61750);
  static IconData file_directory =  FlutterIconData.octicons(61751);
  static IconData file_media =  FlutterIconData.octicons(61752);
  static IconData file_pdf =  FlutterIconData.octicons(61753);
  static IconData file_submodule =  FlutterIconData.octicons(61754);
  static IconData file_symlink_directory =
       FlutterIconData.octicons(61755);
  static IconData file_symlink_file =
       FlutterIconData.octicons(61756);
  static IconData file_zip =  FlutterIconData.octicons(61757);
  static IconData flame =  FlutterIconData.octicons(61758);
  static IconData fold =  FlutterIconData.octicons(61759);
  static IconData gear =  FlutterIconData.octicons(61760);
  static IconData gift =  FlutterIconData.octicons(61761);
  static IconData gist =  FlutterIconData.octicons(61762);
  static IconData gist_secret =  FlutterIconData.octicons(61763);
  static IconData git_branch =  FlutterIconData.octicons(61764);
  static IconData git_commit =  FlutterIconData.octicons(61765);
  static IconData git_compare =  FlutterIconData.octicons(61766);
  static IconData git_merge =  FlutterIconData.octicons(61767);
  static IconData git_pull_request =
       FlutterIconData.octicons(61768);
  static IconData globe =  FlutterIconData.octicons(61769);
  static IconData grabber =  FlutterIconData.octicons(61770);
  static IconData graph =  FlutterIconData.octicons(61771);
  static IconData heart =  FlutterIconData.octicons(61772);
  static IconData history =  FlutterIconData.octicons(61773);
  static IconData home =  FlutterIconData.octicons(61774);
  static IconData horizontal_rule =  FlutterIconData.octicons(61775);
  static IconData hubot =  FlutterIconData.octicons(61776);
  static IconData inbox =  FlutterIconData.octicons(61777);
  static IconData info =  FlutterIconData.octicons(61778);
  static IconData issue_closed =  FlutterIconData.octicons(61779);
  static IconData issue_opened =  FlutterIconData.octicons(61780);
  static IconData issue_reopened =  FlutterIconData.octicons(61781);
  static IconData italic =  FlutterIconData.octicons(61782);
  static IconData jersey =  FlutterIconData.octicons(61783);
  static IconData kebab_horizontal =
       FlutterIconData.octicons(61784);
  static IconData kebab_vertical =  FlutterIconData.octicons(61785);
  static IconData key =  FlutterIconData.octicons(61786);
  static IconData keyboard =  FlutterIconData.octicons(61787);
  static IconData law =  FlutterIconData.octicons(61788);
  static IconData light_bulb =  FlutterIconData.octicons(61789);
  static IconData link =  FlutterIconData.octicons(61790);
  static IconData link_external =  FlutterIconData.octicons(61791);
  static IconData list_ordered =  FlutterIconData.octicons(61792);
  static IconData list_unordered =  FlutterIconData.octicons(61793);
  static IconData location =  FlutterIconData.octicons(61794);
  static IconData lock =  FlutterIconData.octicons(61795);
  static IconData logo_gist =  FlutterIconData.octicons(61796);
  static IconData logo_github =  FlutterIconData.octicons(61797);
  static IconData mail =  FlutterIconData.octicons(61798);
  static IconData mail_read =  FlutterIconData.octicons(61799);
  static IconData mark_github =  FlutterIconData.octicons(61800);
  static IconData markdown =  FlutterIconData.octicons(61801);
  static IconData megaphone =  FlutterIconData.octicons(61802);
  static IconData mention =  FlutterIconData.octicons(61803);
  static IconData milestone =  FlutterIconData.octicons(61804);
  static IconData mirror =  FlutterIconData.octicons(61805);
  static IconData mortar_board =  FlutterIconData.octicons(61806);
  static IconData mute =  FlutterIconData.octicons(61807);
  static IconData no_newline =  FlutterIconData.octicons(61808);
  static IconData note =  FlutterIconData.octicons(61809);
  static IconData octoface =  FlutterIconData.octicons(61810);
  static IconData organization =  FlutterIconData.octicons(61811);
  static IconData package =  FlutterIconData.octicons(61812);
  static IconData paintcan =  FlutterIconData.octicons(61813);
  static IconData pencil =  FlutterIconData.octicons(61814);
  static IconData person =  FlutterIconData.octicons(61815);
  static IconData pin =  FlutterIconData.octicons(61816);
  static IconData plug =  FlutterIconData.octicons(61817);
  static IconData plus =  FlutterIconData.octicons(61818);
  static IconData plus_small =  FlutterIconData.octicons(61819);
  static IconData primitive_dot =  FlutterIconData.octicons(61820);
  static IconData primitive_square =
       FlutterIconData.octicons(61821);
  static IconData project =  FlutterIconData.octicons(61822);
  static IconData pulse =  FlutterIconData.octicons(61823);
  static IconData question =  FlutterIconData.octicons(61824);
  static IconData quote =  FlutterIconData.octicons(61825);
  static IconData radio_tower =  FlutterIconData.octicons(61826);
  static IconData reply =  FlutterIconData.octicons(61827);
  static IconData repo =  FlutterIconData.octicons(61828);
  static IconData repo_clone =  FlutterIconData.octicons(61829);
  static IconData repo_force_push =  FlutterIconData.octicons(61830);
  static IconData repo_forked =  FlutterIconData.octicons(61831);
  static IconData repo_pull =  FlutterIconData.octicons(61832);
  static IconData repo_push =  FlutterIconData.octicons(61833);
  static IconData report =  FlutterIconData.octicons(61834);
  static IconData rocket =  FlutterIconData.octicons(61835);
  static IconData rss =  FlutterIconData.octicons(61836);
  static IconData ruby =  FlutterIconData.octicons(61837);
  static IconData screen_full =  FlutterIconData.octicons(61838);
  static IconData screen_normal =  FlutterIconData.octicons(61839);
  static IconData search =  FlutterIconData.octicons(61840);
  static IconData server =  FlutterIconData.octicons(61841);
  static IconData settings =  FlutterIconData.octicons(61842);
  static IconData shield =  FlutterIconData.octicons(61843);
  static IconData sign_in =  FlutterIconData.octicons(61844);
  static IconData sign_out =  FlutterIconData.octicons(61845);
  static IconData smiley =  FlutterIconData.octicons(61846);
  static IconData squirrel =  FlutterIconData.octicons(61847);
  static IconData star =  FlutterIconData.octicons(61848);
  static IconData stop =  FlutterIconData.octicons(61849);
  static IconData sync =  FlutterIconData.octicons(61850);
  static IconData tag =  FlutterIconData.octicons(61851);
  static IconData tasklist =  FlutterIconData.octicons(61852);
  static IconData telescope =  FlutterIconData.octicons(61853);
  static IconData terminal =  FlutterIconData.octicons(61854);
  static IconData text_size =  FlutterIconData.octicons(61855);
  static IconData three_bars =  FlutterIconData.octicons(61856);
  static IconData thumbsdown =  FlutterIconData.octicons(61857);
  static IconData thumbsup =  FlutterIconData.octicons(61858);
  static IconData tools =  FlutterIconData.octicons(61859);
  static IconData trashcan =  FlutterIconData.octicons(61860);
  static IconData triangle_down =  FlutterIconData.octicons(61861);
  static IconData triangle_left =  FlutterIconData.octicons(61862);
  static IconData triangle_right =  FlutterIconData.octicons(61863);
  static IconData triangle_up =  FlutterIconData.octicons(61864);
  static IconData unfold =  FlutterIconData.octicons(61865);
  static IconData unmute =  FlutterIconData.octicons(61866);
  static IconData unverified =  FlutterIconData.octicons(61867);
  static IconData verified =  FlutterIconData.octicons(61868);
  static IconData versions =  FlutterIconData.octicons(61869);
  static IconData watch =  FlutterIconData.octicons(61870);
  static IconData x =  FlutterIconData.octicons(61871);
  static IconData zap =  FlutterIconData.octicons(61872);
}
